MonsterEncounterTable:
	.db Ooze      Ooze      Ooze      Ooze      Ooze      Ooze      Ooze      Ooze      Slimetoad Slimetoad Slimetoad Slimetoad Scorpion  Scorpion  Scorpion  Scorpion 
	.db Ooze      Ooze      Ooze      Ooze      Ooze      Slimetoad Slimetoad Slimetoad Slimetoad Slimetoad Scorpion  Scorpion  Scorpion  Scorpion  Krag      Krag     
	.db Scorpion  Scorpion  Scorpion  Scorpion  Krag      Krag      Krag      Krag      BlueOoze  BlueOoze  Lochtoad  Lochtoad  Scorpion  Krag      BlueOoze  Lochtoad 
	.db Scorpion  Scorpion  Krag      Krag      BlueOoze  BlueOoze  BlueOoze  BlueOoze  Lochtoad  Lochtoad  Lochtoad  Lochtoad  Scorpion  Krag      BlueOoze  Lochtoad 
	.db BlueOoze  BlueOoze  BlueOoze  BlueOoze  Lochtoad  Lochtoad  Lochtoad  Lochtoad  Phantom   Phantom   Orb       Orb       BlueOoze  Lochtoad  Phantom   Orb      
	.db BlueOoze  BlueOoze  Lochtoad  Lochtoad  Phantom   Phantom   Phantom   Phantom   Orb       Orb       Orb       Orb       BlueOoze  Lochtoad  Phantom   Orb      
	.db Phantom   Phantom   Phantom   Phantom   Orb       Orb       Orb       Orb       RedOoze   RedOoze   Bloodtoad Bloodtoad RedOoze   Bloodtoad RedOoze   Bloodtoad
	.db Phantom   Phantom   Orb       Orb       RedOoze   RedOoze   RedOoze   RedOoze   Bloodtoad Bloodtoad Bloodtoad Bloodtoad Phantom   Orb       RedOoze   Bloodtoad
	.db RedOoze   RedOoze   Bloodtoad Bloodtoad Bloodtoad Bloodtoad Witch     Witch     Witch     Witch     Witch     Witch     Witch     Witch     Witch     Witch    
	.db RedOoze   RedOoze   Bloodtoad Bloodtoad Bloodtoad Bloodtoad Myst      Myst      Myst      Myst      Myst      Myst      Myst      Myst      Myst      Myst     
	.db Witch     Witch     Witch     Witch     Witch     Witch     Myst      Myst      Myst      Myst      Myst      Myst      Demijaw   Demijaw   Kraken    Kraken   
	.db Witch     Witch     Myst      Myst      Demijaw   Demijaw   Demijaw   Demijaw   Demijaw   Demijaw   Kraken    Kraken    Kraken    Kraken    Kraken    Kraken   
	.db Demijaw   Demijaw   Demijaw   Demijaw   Kraken    Kraken    Kraken    Kraken    Scorpius  Scorpius  KingKrag  KingKrag  Scorpius  KingKrag  Demijaw   Kraken   
	.db Demijaw   Demijaw   Kraken    Kraken    Scorpius  Scorpius  Scorpius  Scorpius  KingKrag  KingKrag  KingKrag  KingKrag  Demijaw   Kraken    Scorpius  Scorpius 
	.db Scorpius  Scorpius  Scorpius  Scorpius  KingKrag  KingKrag  KingKrag  KingKrag  Root      Root      RedSnail  RedSnail  Root      RedSnail  Scorpius  KingKrag 
	.db Scorpius  Scorpius  KingKrag  KingKrag  Root      Root      Root      Root      RedSnail  RedSnail  RedSnail  RedSnail  Scorpius  KingKrag  Root      RedSnail 
	.db Root      Root      Root      Root      RedSnail  RedSnail  RedSnail  RedSnail  Spectre   Spectre   BloodOrb  BloodOrb  Spectre   BloodOrb  Root      RedSnail 
	.db Root      Root      RedSnail  RedSnail  Spectre   Spectre   Spectre   Spectre   BloodOrb  BloodOrb  BloodOrb  BloodOrb  Root      RedSnail  Spectre   BloodOrb 
	.db Spectre   Spectre   Spectre   Spectre   BloodOrb  BloodOrb  BloodOrb  BloodOrb  BloodRoot BloodRoot BlueSnail BlueSnail BloodRoot BlueSnail Spectre   BloodOrb 
	.db Spectre   Spectre   BloodOrb  BloodOrb  BloodRoot BloodRoot BloodRoot BloodRoot BlueSnail BlueSnail BlueSnail BlueSnail Spectre   BloodOrb  BloodRoot BlueSnail
	.db BloodRoot BloodRoot BloodRoot BloodRoot BlueSnail BlueSnail BlueSnail BlueSnail MadWitch  MadWitch  DeathMyst DeathMyst MadWitch  DeathMyst MadWitch  DeathMyst
	.db BloodRoot BloodRoot BlueSnail BlueSnail MadWitch  MadWitch  MadWitch  MadWitch  DeathMyst DeathMyst DeathMyst DeathMyst BloodRoot BlueSnail BloodRoot BlueSnail
	.db MadWitch  MadWitch  MadWitch  MadWitch  DeathMyst DeathMyst DeathMyst DeathMyst DeathRoot DeathRoot KingSnail KingSnail DeathRoot KingSnail DeathRoot KingSnail
	.db MadWitch  MadWitch  DeathMyst DeathMyst DeathRoot DeathRoot DeathRoot DeathRoot KingSnail KingSnail KingSnail KingSnail MadWitch  DeathMyst MadWitch  DeathMyst
	.db DeathRoot DeathRoot DeathRoot DeathRoot KingSnail KingSnail KingSnail KingSnail Wraith    Wraith    DeathOrb  DeathOrb  Wraith    DeathOrb  DeathRoot KingSnail
	.db DeathRoot DeathRoot KingSnail KingSnail Wraith    Wraith    Wraith    Wraith    DeathOrb  DeathOrb  DeathOrb  DeathOrb  DeathRoot KingSnail Wraith    DeathOrb 
	.db Wraith    Wraith    Wraith    Wraith    DeathOrb  DeathOrb  DeathOrb  DeathOrb  Blob      Blob      Krakos    Krakos    Wraith    DeathOrb  Blob      Krakos   
	.db Wraith    Wraith    DeathOrb  DeathOrb  Blob      Blob      Blob      Blob      Krakos    Krakos    Krakos    Krakos    Wraith    DeathOrb  Blob      Krakos   
	.db Blob      Blob      Blob      Blob      Krakos    Krakos    Krakos    Krakos    Dragon    Dragon    Kameleon1 Kameleon1 Kameleon1 Kameleon2 Kameleon2 Kameleon2
	.db Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon    Dragon   
